---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubernetes
  namespace: homepage
data:
  kubernetes.yaml: |-
    mode: cluster
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: settings
  namespace: homepage
data:
  settings.yaml: |-
    startUrl: https://dash.crt.house
    target: _self
    title: dash.crt.house
    layout:
      Media:
        style: row
        columns: 3
      "Media Management":
        style: row
        columns: 3
      Column1:
        header: false
        Kubernetes:
          style: column
      Column2:
        header: false
        "Home Automation":
          style: column
        Tools:
          style: column
      Column3:
        header: false
        PiHole:
          style: column
        Web:
          style: column
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-css
  namespace: homepage
data:
  custom.css: ""
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-js
  namespace: homepage
data:
  custom.js: ""
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: docker
  namespace: homepage
data:
  docker.yaml: ""
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: services
  namespace: homepage
data:
  services.yaml: ""
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: widgets
  namespace: homepage
data:
  widgets.yaml: ""
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: proxmox
  namespace: homepage
data:
  proxmox.yaml: ""

